### ISSUE TITLE
lists do not have proper css applied to them

### ISSUE THREAD

**Issue by mikkoh** [Jam3/browser-lessons#4]
![screen shot 2015-04-02 at 3 50 35 pm](https://cloud.githubusercontent.com/assets/496903/6972183/0ee3cbbe-d950-11e4-931d-8937a7a4e7dc.png)

**Comment by jmckinnell** [comment]
@MikkoH See my pull request. https://github.com/Jam3/browser-lessons/pull/5 addresses this.
